ALTER TABLE users
    ADD COLUMN institution VARCHAR(255),
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN updated_at TIMESTAMP,
ADD COLUMN deactivated_at TIMESTAMP,
ADD COLUMN last_login TIMESTAMP,
ADD COLUMN deletion_scheduled_at TIMESTAMP,
ADD COLUMN rgpd_consent BOOLEAN DEFAULT TRUE,
ADD COLUMN notes TEXT,
ADD COLUMN verified BOOLEAN DEFAULT TRUE;

ALTER TABLE users
    ALTER COLUMN password DROP NOT NULL;